project:
  type: book
  output-dir: docs

book:
  title: "CCNs"
  subtitle: "CMS Certification Numbers"
  author: "Andrew Allen Bruce"
  date: "03/31/2026"
  back-to-top-navigation: true
  page-navigation: true
  page-footer: "© Copyright 2026 Andrew Allen Bruce."
  site-url: https://andrewallenbruce.github.io/ccn_notes/
  repo-url: https://github.com/andrewallenbruce/ccn_notes
  chapters:
    - index.qmd
    - state.qmd
    - part: medicare.qmd
      chapters:
        - opo.qmd
        - emergency.qmd
        - hha.qmd
        - esrd.qmd
        - cah.qmd
    - part: medicaid.qmd
      chapters:
        - nf.qmd
        - icf.qmd
        - moh.qmd
    - part: eipps.qmd
      chapters:
        - unit.qmd
        - subunit.qmd
        - swingbed.qmd
    - part: supplier.qmd
      chapters:
        - asc.qmd
        - clia.qmd
        - pxrf.qmd
  appendices:
    - implementation.qmd
    - resources.qmd



