project:
  type: book
  output-dir: docs

execute: 
  eval: true
  echo: true
  warning: false
fig-align: center
fig-height: 4
fig-width: 6

book:
  title: "CCNs"
  subtitle: "CMS Certification Numbers"
  author: "Andrew Allen Bruce"
  date: "03/31/2026"
  back-to-top-navigation: true
  page-navigation: true
  page-footer: "© Copyright 2026 Andrew Allen Bruce."
  site-url: https://andrewallenbruce.github.io/ccn_notes/
  repo-url: https://github.com/andrewallenbruce/ccn_notes
  
  chapters:
    - index.qmd
    - state.qmd
    - part: medicare.qmd
      chapters:
        - opo.qmd
        - emergency.qmd
        - hha.qmd
        - esrd.qmd
        - cah.qmd
    - part: medicaid.qmd
      chapters:
        - nf.qmd
        - icf.qmd
        - moh.qmd
    - part: eipps.qmd
      chapters:
        - unit.qmd
        - subunit.qmd
        - swingbed.qmd
    - part: supplier.qmd
      chapters:
        - asc.qmd
        - clia.qmd
        - pxrf.qmd
  appendices:
    - implementation.qmd
    - resources.qmd

format:
  html:
    grid:
      body-width: 1000px
    backgroundcolor: "#FFFFFF"
    number-sections: false
    anchor-sections: true
    code-fold: false
    code-link: true
    code-overflow: scroll
    code-tools: true
    code-copy: true
    date: last-modified
    embed-resources: false
    footnotes-hover: true
    reference-location: margin
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    urlcolor: "#FC4C02"
    linkcolor: "darkred"
    fontcolor: "#43466b"
    default-image-extension: png
    fig-cap-location: margin
    fig-width: 5
    fig-asp: 0.67
    fig-align: center
    fig-dpi: 300
    fig-format: png
    smooth-scroll: true
    syntax-highlighting: tango
