project:
  type: book
  output-dir: docs

execute: 
  eval: true
  echo: true
  message: true
  warning: false

book:
  title: "CCNs"
  subtitle: "CMS Certification Numbers"
  author: "Andrew Allen Bruce"
  back-to-top-navigation: true
  page-navigation: true
  page-footer: "© Copyright 2026 Andrew Allen Bruce."
  site-url: https://andrewallenbruce.github.io/ccn_notes/
  repo-url: https://github.com/andrewallenbruce/ccn_notes
  
  chapters:
    - index.qmd
    - state.qmd
    - opo.qmd
    - erh.qmd
    - part: medicare.qmd
      chapters:
        - hha.qmd
        - esrd.qmd
        - ltch.qmd
        - rhc.qmd
        - irf.qmd
        - cah.qmd
    - eipps.qmd
    - swing.qmd
    - medicaid.qmd
    - snf_nf.qmd
    - part: supplier.qmd
      chapters:
        - asc.qmd
        - clia.qmd
        - pxrf.qmd
  appendices:
    - vctrs.qmd
    - resources.qmd

format:
  html:
    anchor-sections: true
    backgroundcolor: "#FFFFFF"
    code-fold: false
    code-link: true
    code-overflow: scroll
    code-tools: true
    code-copy: true
    date: last-modified
    default-image-extension: png
    embed-resources: false
    fig-cap-location: margin
    fig-width: 5
    fig-asp: 0.67
    fig-align: center
    fig-dpi: 300
    fig-format: png
    footnotes-hover: true
    fontcolor: "#43464b"
    grid:
      body-width: 800px
    linkcolor: "darkred"
    number-sections: false
    reference-location: document
    smooth-scroll: true
    syntax-highlighting: tango
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    urlcolor: "#FC4C02"
