---
output: html_document
editor_options: 
  chunk_output_type: console
---
# ESRDs

```{r setup}
#| message: false
#| warning: false
#| echo: false
#| cache: false
#| comment: ""
library(ccn)
```

## Facility Ranges

The last four characters of a Provider CCN represent the facility type and a unique
identifier. The facility type is encoded in the third character of the last four
characters. The table below summarizes the valid facility type codes and their
corresponding ranges. 

```{r}
#| label: esrd-ranges
#| echo: false
#| message: false
ccn::medicare_ranges |>
  collapse::sbt(
    start == 1L | 
    start == 2000L | 
    start == 3300L | 
    abbr == "ESRD", 
    -start, 
    -end) |>
  gt::gt() |>
  gt::tab_options(quarto.disable_processing = TRUE) |>
  gtExtras::gt_theme_nytimes() |>
  gt::tab_style(
    style = gt::cell_text(
      font = gt::google_font(name = "JetBrains Mono"), 
      color = "grey60", 
      size = "small"),
    locations = gt::cells_body(columns = range)
  ) |>
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_body(columns = abbr)
  ) |>
  gt::tab_style(
    style = gt::cell_text(color = "grey50", size = "small"),
    locations = gt::cells_body(columns = desc)
  )
```

## Examples

```{r}
ccn:::get_pin("esrd") |> 
  collapse::descr()
```

