---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Introduction

```{r setup}
#| message: false
#| warning: false
#| echo: false
#| cache: false
#| comment: ""
library(ccn)
```

A __CMS Certification Number__ is a uniform way of identifying a healthcare
provider or supplier that has or currently does participate in the Medicare and/or Medicaid programs.

The CCN is used to track provider agreements and cost reports. The NPI^[National
Provider Identifier] and PTAN^[Provider Transaction Account Number] are
tied to an entity's CCN. The RO^[CMS Regional Office], not the SA^[State Agency] or MAC^[Medicare Administrative Contractor], assigns the CCN and maintains adequate controls.

::: {#tip-ccn .callout-tip}

## One Term to Rule Them All

In [2007](https://www.cms.gov/medicare/provider-enrollment-and-certification/surveycertificationgeninfo/policy-and-memos-to-states-and-regions-items/cms1206256), the __CCN__ replaced the following terms: 

   * Medicare Provider Number
   * Medicare Identification Number
   * OSCAR^[Online Survey, Certification, and Reporting System.] Number

:::

## Canonical Format

A __*canonically valid* CCN__ is an alphanumeric string, either 6 or 10 characters in
length, that encodes a provider/supplier's state and facility type.

