---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Medicare

```{r}
#| label: setup
#| message: false
#| warning: false
#| echo: false
#| cache: false
#| comment: ""
library(ccn)
library(provider)
library(collapse)
```

Providers and Suppliers paid under *Medicare Part A* have **6 digit** CCNs. The
first two characters represent the state in which the provider is located. The
last four characters identify the type of facility.

## Facility Ranges

```{r}
#| label: medicare-ranges
#| echo: false
#| message: false
ccn::medicare_ranges |>
  collapse::gby(abbr) |>
  collapse::fsummarise(
    desc = collapse::fslice(desc),
    range = toString(range)
  ) |>
  collapse::slt(abbr, range, desc) |>
  gt::gt() |>
  gt::cols_align("left", columns = "range") |>
  gt::tab_options(
    table.width = gt::pct(100),
    quarto.disable_processing = TRUE
  ) |>
  gtExtras::gt_theme_nytimes() |>
  gt::tab_style(
    style = gt::cell_text(
      font = gt::google_font(name = "JetBrains Mono"),
      color = "grey60",
      size = "small"
    ),
    locations = gt::cells_body(columns = range)
  ) |>
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_body(columns = abbr)
  ) |>
  gt::tab_style(
    style = gt::cell_text(color = "grey50", size = "small"),
    locations = gt::cells_body(columns = desc)
  )
```

## Examples

```{r}
#| label: load-pin
#| echo: false
#| message: false
hosp <- ccn:::get_pin("hosp")
```

### Overview

```{r}
#| label: decode
#| echo: false
#| message: false
collapse::qtable(ccn::decode_ccnr(hosp$ccn)[.c(facility, form)])
```

#### Units/Subunits

```{r}
#| label: units-subunits
#| echo: false
#| message: false
hosp |>
  collapse::roworder(ccn) |>
  collapse::mtt(ccn = substring(ccn, 1L, 6L)) |>
  collapse::sbt(stringi::stri_detect_regex(ccn, "[ABEFLJGHK]")) |>
  gt::gt() |>
  gtExtras::gt_theme_nytimes() |>
  gt::tab_options(
    table.width = gt::pct(100),
    quarto.disable_processing = TRUE
  )
```

#### Subgroup Counts

```{r}
#| label: subgroup-counts
#| echo: false
#| message: false
hcount <- hosp |>
  collapse::sbt(!is.na(subgroup)) |>
  collapse::sbt(
    stringi::stri_detect_regex(subgroup, "REH[:]", negate = TRUE)
  ) |>
  collapse::fcount(subgroup) |>
  collapse::roworder(-N)

# hcount |>
#   collapse::sbt(N > 11) |>
#   gt::gt() |>
#   gtExtras::gt_theme_nytimes() |>
#   gt::tab_options(
#     table.width = gt::pct(100),
#     quarto.disable_processing = TRUE
#   )
# 
# hcount |>
#   collapse::sbt(N <= 11) |>
#   gt::gt(groupname_col = "N", row_group_as_column = TRUE) |>
#   gtExtras::gt_theme_nytimes() |>
#   gt::tab_options(
#     table.width = gt::pct(100),
#     quarto.disable_processing = TRUE
#   )
```

#### REHs

```{r}
#| label: reh
#| echo: false
#| message: false
hosp |>
  collapse::sbt(!is.na(subgroup)) |>
  collapse::sbt(stringi::stri_detect_regex(subgroup, "REH[:]")) |>
  gt::gt() |>
  gtExtras::gt_theme_nytimes() |>
  gt::tab_options(
    table.width = gt::pct(100),
    quarto.disable_processing = TRUE
  )
```
