---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Hospitals

```{r setup}
#| message: false
#| warning: false
#| echo: false
#| cache: false
#| comment: ""
library(ccn)
```

```{r}
#| label: pkg-version
#| echo: false
paste("ccn version:", sQuote(utils::packageVersion("ccn")), "loaded") |> cat()
```

## Hospital Ranges

The last three characters of a Medicaid-Only Hospital CCN represent the facility range. The facility type is encoded in the third character of the last four
characters. The table below summarizes the valid facility type codes and their
corresponding ranges. 

```{r}
#| label: medicaid-hospital-ranges
#| echo: false
#| message: false
ccn::medicaid_ranges |>
  collapse::slt(abbr, desc, range) |>
  collapse::roworder(range) |>
  gt::gt() |>
  gt::tab_options(quarto.disable_processing = TRUE) |>
  gtExtras::gt_theme_nytimes() |>
  gt::tab_style(
    style = gt::cell_text(
      font = gt::google_font(name = "JetBrains Mono"),
      color = "grey60",
      size = "small"
    ),
    locations = gt::cells_body(columns = range)
  ) |>
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_body(columns = abbr)
  ) |>
  gt::tab_style(
    style = gt::cell_text(color = "grey50", size = "small"),
    locations = gt::cells_body(columns = desc)
  )
```

## Examples

```{r examples}
parse("01J008")
decode("01J008")
purrr::map(c("01J008", "A5J508"), ccn::as_data_frame) |> 
  collapse::rowbind(fill = TRUE)
```


```{r}
purrr::map(c("050599", "440058"), ccn::as_data_frame) |> 
  collapse::rowbind(fill = TRUE)

ccn:::get_pin("hosp") |> 
  collapse::sbt(
    !is.na(subgroup)
    # ccn == "440058"
    # subgroup == "Other, General, Acute, ORGAN TRANSPLANT UNIT"
    ) |>
  collapse::fcount(subgroup) |> 
  collapse::roworder(-N) |> 
  print(n = Inf)
```

