---
output: html_document
editor_options: 
  chunk_output_type: console
---

# OPO

```{r setup}
#| message: false
#| warning: false
#| echo: false
#| cache: false
#| comment: ""
library(ccn)
source("code/gt_theme.R")
x <- ccn:::get_pin("opo")
```

<br>

Organ procurement organizations (OPOs) are assigned a 6-digit alphanumeric CCN.
The first 2 digits identify the State code. The third digit is the alpha
character P. The remaining 3 digits are the unique facility identifier.

```{r}
#| label: opo-example
organ("05P001") |> 
  as_data_frame() |> 
  str()
```

## Codes

```{r}
x$opo_codes |> 
  collapse::roworder(code) |> 
  gt::gt() |> 
  gt::tab_options(quarto.disable_processing = TRUE) |> 
  gtExtras::gt_theme_nytimes() |> 
  gt::tab_style(
    style = gt::cell_text(
      font = gt::google_font(name = "JetBrains Mono"), color = "grey30", size = "small"), 
    locations = gt::cells_body(columns = c(code, opo))) |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"), 
    locations = gt::cells_body(columns = code)) |> 
  gt::tab_style(
    style = gt::cell_text(color = "grey25"), 
    locations = gt::cells_body(columns = opo))
```


## Counties

```{r}
#| label: opo-county
cnty <- x$opo_county |>
  collapse::slt(-code) |> 
  collapse::roworder(state, county) |>
  collapse::fgroup_by(state) |>
  collapse::fsummarise(counties = length(county)) |> 
  collapse::fungroup()

x$opo_county |> 
  collapse::slt(-county) |> 
  collapse::funique() |> 
  collapse::fgroup_by(state) |>
  collapse::fsummarise(codes = toString(code)) |> 
  collapse::join(cnty, verbose = 0L) |> 
  collapse::roworder(state) |> 
  gt::gt() |> 
  gt::tab_options(quarto.disable_processing = TRUE) |> 
  gtExtras::gt_theme_nytimes() |> 
  gt::tab_style(
    style = gt::cell_text(
      font = gt::google_font(name = "JetBrains Mono"), color = "grey30", size = "small"), 
    locations = gt::cells_body(columns = c(codes, counties))) |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"), 
    locations = gt::cells_body(columns = state)) |> 
  gt::tab_style(
    style = gt::cell_text(color = "grey25"), 
    locations = gt::cells_body(columns = state))
```

### Active

```{r}
x$opo_active |> 
  collapse::roworder(ccn) |>
  collapse::slt(-region, -orig_date) |> 
   gt::gt() |> 
   gt::tab_options(quarto.disable_processing = TRUE) |> 
  gtExtras::gt_theme_nytimes() |> 
  gt::tab_style(
    style = gt::cell_text(
      font = gt::google_font(name = "JetBrains Mono"), color = "grey30", size = "small"), 
    locations = gt::cells_body(columns = ccn)) |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"), 
    locations = gt::cells_body(columns = state)) |> 
  gt::tab_style(
    style = gt::cell_text(color = "grey50", size = "small"), 
    locations = gt::cells_body(columns = opo))
```

### Approved Transplant Programs

```{r}
ccn:::get_pin("txc") |> 
  collapse::slt(code = txc_code, desc = txc_type) |> 
  collapse::funique() |> 
  gt::gt() |> 
  gt::tab_options(quarto.disable_processing = TRUE) |> 
  gtExtras::gt_theme_nytimes() |> 
  gt::tab_style(
    style = gt::cell_text(
      font = gt::google_font(name = "JetBrains Mono"), color = "grey30", size = "small"), 
    locations = gt::cells_body(columns = code)) |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"), 
    locations = gt::cells_body(columns = code)) |> 
  gt::tab_style(
    style = gt::cell_text(color = "grey50", size = "small"), 
    locations = gt::cells_body(columns = desc))
```


```{r}
ccn:::get_pin("txc") |> 
  collapse::slt(-txc_type) |> 
  collapse::rnm(code = optn_code, txc = txc_code) |> 
  collapse::funique() |> 
  collapse::roworder(ccn, state, code) |>
  collapse::fgroup_by(ccn, state, code) |>
  collapse::fsummarise(txc = toString(txc)) |> 
  collapse::fungroup() |> 
  gt::gt() |> 
  gt::tab_options(quarto.disable_processing = TRUE) |> 
  gtExtras::gt_theme_nytimes() |> 
  gt::tab_style(
    style = gt::cell_text(
      font = gt::google_font(name = "JetBrains Mono"), color = "grey30", size = "small"), 
    locations = gt::cells_body(columns = c(ccn, txc))) |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"), 
    locations = gt::cells_body(columns = state)) |> 
  gt::tab_style(
    style = gt::cell_text(color = "grey50", size = "small"), 
    locations = gt::cells_body(columns = code))
```

