---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Resources

  - [CMS Manual](https://www.cms.gov/regulations-and-guidance/guidance/manuals/downloads/som107c02.pdf)
  - [ResDAC 1](https://resdac.org/cms-data/variables/full-cms-certification-number-provider)
  - [ResDAC 2](https://resdac.org/cms-data/variables/provider-number)
  - [The Joint Commission](https://manual.jointcommission.org/releases/TJC2025A/DataElem0276.html)
  - [QCOR](https://qcor.cms.gov/main.jsp)
  - [Policy & Memos to State and CMS Locations](https://www.cms.gov/medicare/health-safety-standards/quality-safety-oversight-general-information/policy-memos/policy-memos-states-regions)
  - [CMS Glossary](https://www.cms.gov/glossary)

## Valdosta CMS Entities

::: {.list-table}
- - Entity
  - Name

- - Ambulatory Surgical Center (ASC)
  - AZALEA SURGERY CENTER
  - CATARACT AND LASER SURGERY CTR OF SOUTH GA, PC
  - ENT OF SOUTH GEORGIA SURGERY CENTER, LLC
  - EYE ASSOCIATES SURGERY CTR
  - HUGHSTON SURGICAL CENTER OF VALDOSTA, LLC
  - NORTH OAK AMBULATORY SURGERY CENTER, LLC
  - PLASTIC SURGERY OPERATIVE SUITE, LLC
  - SOUTHERN OB/GYN AMBULATORY SURGERY CENTER
  - SOUTHWELL LOWNDES ENDOSCOPY CENTER
  - SOUTHWELL VALDOSTA ENDOSCOPY CENTER
  - UROLOGICAL CLINIC OF VALDOSTA ASC, INC
  - VALDOSTA FOOT & ANKLE SURGERY
  - VOA AMBULATORY SURG CTR

- - End Stage Renal Disease Facility (ESRD)
  - OAK STREET DIALYSIS
  - US RENAL CARE CENTRAL VALDOSTA
  - US RENAL CARE SOUTH GEORGIA DIALYSIS
  - US RENAL CARE VALDOSTA HOME PROGRAM
  - VALDOSTA DIALYSIS CLINIC
  - VALDOSTA HOME TRAINING
:::


## Federally Qualified Health Center
1. NORTHSIDE FAMILY HEALTH CENTER
2. SOUTH CENTRAL PRIMARY CARE-ASHLEY STREET

## Home Health Agency
1. ADORATION HOME HEALTH
2. AMEDISYS HOME HEALTH OF VALDOSTA
3. GEORGIA HOME HEALTH SERVICES

## Hospice
1. BETHANY HOSPICE AND PALLIATIVE CARE, LLC
2. HEART OF HOSPICE VALDOSTA
3. HOSPICE OF SOUTH GEORGIA
4. PRUITTHEALTH HOSPICE-VALDOSTA

## Hospital
1. GREENLEAF CENTER
2. SGMC HEALTH
3. US AIR FORCE HOSP

## Intermediate Care Facility
1. PRUITTHEALTH-PARKWOOD, LLC

## CLIA Laboratory
1. 9 LINE HEALTH, LLC
2. ADORATION HOME HEALTH CARE GEORGIA, LLC
3. AIRPORT CLINIC INCORPORATED
4. ALLIANCE RESEARCH AND TECHNOLOGY, LLC
5. AMEDISYS GA LLC DBA AMEDISYS HOME HLTH OF VALDOSTA
6. APPLECARE VALDOSTA
7. AR PSYCHIATRIC & COUNSELING CENTER
8. ARUNAS URBONAS MD PLLC
9. AZALEA SURGERY CENTER
10. AZALEA WOMENS CENTER
11. BARNES HEALTH CARE SERVICES
12. BEHAVIORAL HEALTH SERVICES OF SOUTH GEORGIA
13. BEHAVIORAL HEALTH SERVICES OF SOUTH GEORGIA
14. BENNETT P HOGAN MD PC
15. BETHANY HOSPICE
16. BPC PLASMA, INC - VALDOSTA
17. BRIAN C GRINER, MD LLC
18. BRIDGEWAY RECOVERY CENTER
19. CANOPY AT AZALEA GROVE, THE
20. CARE MEDICAL CENTER
21. CATARACT AND LASER SURGRY CTR OF SOUTH GEORGIA, PC
22. CHANCY DRUGS VALDOSTA
23. COLE DERMATOLOGY, LLC
24. CRH CARDIOLOGY GROUP - VALDOSTA
25. DCA OF CENTRAL VALDOSTA LLC DBA
26. DCA OF SO GA, LLC
27. DIABETES MANAGEMENT CENTER
28. DR SUNIL T PERSAUD
29. ENT OF SOUTH GEORGIA SURGERY CENTER, LLC
30. EYE ASSOCIATES OF SOUTH GA, LLC
31. EYE ASSOCIATES SURGERY CENTER
32. FP-PEACHTREE IMMEDIATE CARE VDW
33. FP-PEACHTREE IMMEDIATE CARE VLD
34. GEORGIA CVS PHARMACY, LLC DBA CVS/PHARMACY #04534
35. GHHS HEALTHCARE, LLC
36. GRACE HOSPICE, LLC
37. GREENLEAF CENTER
38. HOGAN'S PHARMACY
39. HOSPICE OF SOUTH GA
40. HUGHSTON MEDICAL GROUP - VALDOSTA
41. HUGHSTON SURGICAL CENTER OF VALDOSTA, LLC
42. IT'S JUST BLOOD DIAGNOSTIC TESTING CENTER LLC
43. JOHN D ANDERSON MD
44. JOSE MEDINA MD
45. KIDS HEALTH OF VALDOSTA
46. LANGDALE HOSPICE HOUSE
47. LANGDALE PLACE
48. LOWNDES COUNTY FIRE AND RESCUE
49. LOWNDES COUNTY HEALTH DEPARTMENT
50. LOWNDES COUNTY JAIL
51. LOWNDES COUNTY SCHOOLS
52. MIDWIFE ME ITD DBA RED MOON MIDWIFERY
53. NATIONAL FAMILY MEDICAL ASSOCIATES OF GEORGIA LLC
54. NATIONWIDE MEDICAL & DIAGNOSTIC SERVICES
55. NORTH OAK FAMILY MEDICINE LLC
56. NORTHSIDE FAMILY HEALTH
57. NRA VALDOSTA GEORGIA, LLC
58. OAK STREET DIALYSIS
59. OCTAPHARMA PLASMA, INC
60. OPTIONS NOW, A LIFE CHOICE CLINIC
61. PACKAGING CORPORATION OF AMERICA
62. PARROTT MEDICAL CLINIC PC
63. PARTNERSHIP HEALTH CENTER
64. PARTNERS IN HEALTH MANAGEMENT LLC
65. PATHWAY TO HOPE COUNSELING SERVICES, INC
66. PEDIATRIA HEALTHCARE LLC DBA AVEANNA HEALTHCARE
67. PLASTIC SURGERY OPERATIVE SUITE LLC
68. PREMISE HEALTH OF GEORGIA MEDICAL PC
69. PREMISE HEALTH OF GEORGIA MEDICAL, PC
70. PRUITTHEALTH-HOLLY HILL, LLC
71. PRUITTHEALTH-HOME FIRST, INC
72. PRUITTHEALTH-HOSPICE-VALDOSTA
73. PRUITTHEALTH-LAKEHAVEN, LLC
74. PRUITTHEALTH-PARKWOOD, LLC
75. PRUITTHEALTH-PHARMACY SERVICES-VALDOSTA, INC
76. PRUITTHEALTH-VALDOSTA, LLC
77. PRUITTHEALTH-VALDOSTA, LLC
78. PRUITTHEALTH-CRESTWOOD, LLC
79. PUBLIX PHARMACY #0430
80. PUBLIX PHARMACY #1435
81. RIGHT CHOICE LAB SERVICES, LLC
82. RURAL URGENT CARE
83. SCINTILLA CHARTER ACADEMY
84. SEPA PC AT AZALEA VALDOSTA GEORGIA
85. SGMC CARDIAC ELECTROPHYSIOLOGY
86. SGMC CARDIOLOGY
87. SGMC CARDIOVASCULAR INSTITUTE
88. SGMC FAMILY MEDICINE-OAK STREET
89. SGMC GENERAL SURGERY
90. SGMC HEALTH
91. SGMC HEALTHCARE SOUTH
92. SGMC HEALTH SMITH NORTHVIEW HOSPITAL
93. SGMC INTERNAL MEDICINE-PARK AVENUE
94. SGMC NEUROLOGY & NEUROSCIENCE
95. SGMC PRIMARY CARE CONNELL
96. SGMC PRIMARY CARE GREYSTONE
97. SGMC PRIMARY CARE KINGS WAY
98. SGMC PRIMARY CARE-NORTHSIDE DR
99. SGMC-SMITH NORTHVIEW CAMPUS
100. SGMC URGENT CARE-GRIFFIN AVENUE
101. SGMC URGENT CARE NORTH VALDOSTA
102. SGMC UROLOGY
103. SGMC VALDOSTA MEDICAL CLINIC
104. SGMC WOMENS HEALTH - OAK
105. SMITH CLINIC, LLC
106. SOUTH CENTRAL PRIMARY CARE ASHLEY STREET
107. SOUTHERN HOME CARE SERVICES, INC
108. SOUTHERN OB/GYN AMBULATORY SURGERY CENTER
109. SOUTHERN OB/GYN ASSOCIATES PC
110. SOUTHERN PEDIATRIC CLINIC ACUTE CARE
111. SOUTHERN PEDIATRIC CLINIC, LLC
112. SOUTHERN PODIATRY GROUP PC
113. SOUTH GA MED CTR DEPT PULMONARY SVCS
114. SOUTH GEORGIA EYE PARTNERS
115. SOUTH GEORGIA MEDICAL ASSOCIATES PC
116. SOUTH GEORGIA MEDICAL CENTER EMS
117. SOUTH GEORGIA PEDIATRICS & ALLERGY CTR
118. SOUTH GEORGIA TOXICOLOGY, LLC
119. SOUTHLAND URO+GYNECOLOGY, LLC
120. SOUTHWELL AMBULATORY, INC
121. SOUTHWELL AMBULATORY, INC
122. SOUTHWELL AMBULATORY, INC
123. SOUTHWELL AMBULATORY, INC DBA SOUTHWELL LOWNDES
124. SOUTHWELL GASTROENTEROLOGY
125. SOUTHWELL GASTROENTEROLOGY
126. SOUTHWELL OB/GYN
127. THACKER DERMATOLOGY, LLC
128. THE HOWARD CENTER FOR WOMENS HEALTH
129. TREATMENT CENTER OF VALDOSTA
130. UC-PEACHTREE IMMEDIATE CARE VDW
131. UC-PEACHTREE IMMEDIATE CARE VLD
132. UROLOGICAL CLINIC OF VALDOSTA AMBULATORY SURGICAL
133. U SAVE IT PHARMACY
134. USRC VALDOSTA HOME PROGRAM, LLC
135. VALDOSTA CBOC
136. VALDOSTA CHILDREN'S HEALTHCARE
137. VALDOSTA CHILDREN'S HEALTHCARE
138. VALDOSTA CITY SCHOOLS DISTRICT
139. VALDOSTA EYE CENTER
140. VALDOSTA FAMILY MEDICINE ASSOCIATES
141. VALDOSTA FIRE DEPARTMENT
142. VALDOSTA FOOT AND ANKLE CLINIC
143. VALDOSTA HEALTH & WELLNESS CLINIC
144. VALDOSTA HOME TRAINING
145. VALDOSTA INTERNAL MEDICINE
146. VALDOSTA ORTHOPEDIC ASSOCIATES
147. VALDOSTA ORTHOPEDIC ASSOCIATES, PC
148. VALDOSTA PSYCHIATRIC ASSOCIATES
149. VALDOSTA STATE PRISON
150. VALDOSTA STATE UNIVERSITY HEALTH CENTER
151. VALDOSTA TRANSITIONAL CENTER
152. VALDOSTA WEIGHT LOSS & WELLNESS
153. VALDOSTA WELLNESS AND SKIN CLINIC LLC
154. VEEDHATA OM LLC DBA PRIME DIAGNOSTICS
155. VEMA HOLISTIC HEALTH, LLC
156. VOA AMBULATORY SURGERY CENTER
157. WALGREENS #17706
158. WALGREENS #6899
159. WALGREENS #9305
160. WALMART PHARMACY 10-2615
161. WALMART PHARMACY 10-6732
162. WALMART PHARMACY 10-899
163. WIREGRASS GEORGIA TECH COLLEGE STUDENT HLTH CTR
164. WOMENS HEALTH- PATTERSON

## SNF/NF (Dually Certified)
1. PRUITTHEALTH - CRESTWOOD, LLC
2. PRUITTHEALTH - HOLLY HILL, LLC
3. PRUITTHEALTH - LAKEHAVEN, LLC
4. PRUITTHEALTH - VALDOSTA, LLC