---
output: html_document
editor_options: 
  chunk_output_type: console
---

# SNF

```{r setup}
#| message: false
#| warning: false
#| echo: false
#| cache: false
#| comment: ""
library(ccn)
library(collapse)
source("code/gt_theme.R")
hrsa <- collapse::gv(ccn:::get_pin("snf_hrsa"), c(1:7, 9:12))
snf <- ccn:::get_pin("snf")
snf <- snf[substr(snf$ccn, 1L, 6L) %!iin% substr(hrsa$ccn, 1L, 6L), ]
```

### Overview

```{r}
#| label: snf-overview
#| echo: false
#| message: false
ov <- hrsa |>
  collapse::rsplit(~.id) |>
  purrr::map(cheapr::overview)

list(
  all = ov$`SNF All`$numeric,
  dist = ov$`SNF Dist`$numeric,
  dual = ov$`SNF Dual`$numeric
) |>
  collapse::rowbind(idcol = "id") |>
  collapse::slt(id, col, uniq = n_unique, mean:hist) |>
  collapse::roworder(col, id) |>
  tibble::as_tibble() |>
  gt::gt(
    rowname_col = "id",
    groupname_col = "col",
    row_group_as_column = TRUE
  ) |>
  gt::tab_options(
    table.width = gt::pct(100),
    quarto.disable_processing = TRUE
  ) |>
  gt::fmt_auto() |>
  gtExtras::gt_theme_nytimes() |>
  gt::tab_style(
    style = gt::cell_text(
      font = gt::google_font(name = "JetBrains Mono"),
      color = "grey50",
      size = "small"
    ),
    locations = gt::cells_body()
  ) |>
  gt::tab_style(
    style = gt::cell_text(
      align = "right",
      weight = "bold",
      size = "small"
    ),
    locations = gt::cells_row_groups()
  ) |>
  gt::tab_style(
    style = gt::cell_text(
      color = "grey50",
      weight = "bold",
      size = "small"
    ),
    locations = gt::cells_stub()
  )

list(
  all = ov$`SNF All`$categorical,
  dist = ov$`SNF Dist`$categorical,
  dual = ov$`SNF Dual`$categorical
) |>
  collapse::rowbind(idcol = "id") |>
  collapse::slt(id, col, uniq = n_unique, min, max) |>
  collapse::roworder(col, id) |>
  tibble::as_tibble() |>
  gt::gt(
    rowname_col = "id",
    groupname_col = "col",
    row_group_as_column = TRUE
  ) |>
  gt::tab_options(
    table.width = gt::pct(100),
    quarto.disable_processing = TRUE
  ) |>
  gtExtras::gt_theme_nytimes() |>
  gt::tab_style(
    style = gt::cell_text(
      font = gt::google_font(name = "JetBrains Mono"),
      color = "grey50",
      size = "small"
    ),
    locations = gt::cells_body()
  ) |>
  gt::tab_style(
    style = gt::cell_text(
      align = "right",
      weight = "bold",
      size = "small"
    ),
    locations = gt::cells_row_groups()
  ) |>
  gt::tab_style(
    style = gt::cell_text(
      color = "grey50",
      weight = "bold",
      size = "small"
    ),
    locations = gt::cells_stub()
  )
```

### Parse


```{r}
#| label: snf-parse
#| echo: false
#| message: false
hrsa |> 
  collapse::gby(.id, sub) |> 
  collapse::fsummarise(
    Medicare = collapse::fsum(beds_mcr),
    Dual = collapse::fsum(beds_dual),
    Certified = collapse::fsum(beds_cert),
    Total = collapse::fsum(beds_tot)
  ) |> 
  gt::gt(
    rowname_col = ".id",
    groupname_col = "sub",
    row_group_as_column = TRUE
  ) |>
  gt::tab_options(
    table.width = gt::pct(100),
    quarto.disable_processing = TRUE
  ) |>
  gtExtras::gt_theme_nytimes() |>
  gt::tab_style(
    style = gt::cell_text(
      font = gt::google_font(name = "JetBrains Mono"),
      color = "grey50",
      size = "small"
    ),
    locations = gt::cells_body()
  ) |>
  gt::tab_style(
    style = gt::cell_text(
      align = "right",
      weight = "bold",
      size = "small"
    ),
    locations = gt::cells_row_groups()
  ) |>
  gt::tab_style(
    style = gt::cell_text(
      color = "grey50",
      weight = "bold",
      size = "small"
    ),
    locations = gt::cells_stub()
  )
```

