---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Swing-Beds

```{r}
#| label: setup
#| message: false
#| warning: false
#| echo: false
#| cache: false
#| comment: ""
library(ccn)
library(provider)
library(collapse)
```

## Hospital Providers of Extended Care Services

"Swing-bed" is a reimbursement term that means the care and reimbursement for
the care of a patient in, for instance, a Rural Emergency Hospital or Critical
Access Hospital. The facility "swings" from Acute Care to post-hospital care in
Skilled Nursing care. A Swing-Bed Hospital refers to a hospital participating in
Medicare with approval from CMS to provide post-hospital SNF care and meets the
requirements specified in *§482.66* (hospital) or *§485.645* (CAH).

Swing-bed certification is a separate approval from the certification to operate
as a hospital. Termination of the swing-beds by CMS, voluntarily or otherwise,
does not affect the continuing operation of the provider. Swing-beds do not have
to be separated from acute patients though the facility may choose to do so.
Patients do not have to move to a different location in the facility when
changing from acute care status to swing-bed status unless the facility requires
it. There is no Length of Stay restriction for a swing-bed patient, no required
discharge to a Nursing Nome and no Transfer Agreement. Patients *may* be
discharged to a Nursing Home but it is not required.

A medical order in the chart by the physician is required to change status from
acute care to swing-bed because the patient is being discharge from acute care
status and admitted to swing-bed status. This is necessary for reimbursement
purposes because the billing and reimbursement change or "swing." Accordingly,
the facility is given a sub-provider number for billing swing-bed services.

For Medicare patients, a 3-day qualifying stay in any hospital or CAH is
required to prior to admission to a swing-bed and the admission must be for
treatment of the same condition. This 3-day qualifying stay only applies to a
Medicare patient. Section 1883 of the Act authorizes payment under Medicare for
post-hospital SNF services provided by any hospital that meets the requirements
at 42 CFR 482.66.

## Calculation of Bed Count

Exclude from the bed count newborn and intensive care beds. A hospital licensed
for more than 100 beds may be eligible for swing-bed approval if it utilizes and
staffs for fewer than 100 beds.

## Example

```r
x <- vctrs::vec_rbind(
  hospital(loc_type = "swing"),
  hospital(subgroup = subgroups(swing = TRUE)))

x

cheapr::counts(x$sub_group) |> collapse::roworderv(
  "count", 
  decreasing = TRUE) |> 
  collapse::qTBL() |> 
  print(n = Inf)

cheapr::counts(x$loc_type) |> 
  collapse::roworderv(
  "count", 
  decreasing = TRUE) |> 
  collapse::qTBL() |> 
  print(n = Inf)

cheapr::counts(x$org_type) |> 
  collapse::roworderv(
  "count", 
  decreasing = TRUE) |> 
  collapse::qTBL() |> 
  print(n = Inf)
```


```r
vctrs::vec_size(x$ccn)
vctrs::vec_unique_count(x$ccn)

xc <- vctrs::vec_unique(x$ccn)
xc <- as_ccn(xc)

xr <- as_ccnr(xc)
xr <- decode_ccnr(xr)
xr <- collapse::ss(xr, j = 1:5, check = FALSE)
xr <- collapse::rsplit(xr, xr$form)

xr$care$parent <- NULL

collapse::qtab(xr$care[.c(state, facility)], sort = TRUE, drop = TRUE)
```


```r
length(xr$unit$parent)
sum(nchar(xr$unit$parent) == 5L, na.rm = TRUE)
index_ccn_types(as_ccn(xr$unit$parent))
```

